server:
  port: 80
logging:
  level:
    org.springframework.web: INFO
    com.mtv: DEBUG
 
spring:
  jpa:
    hibernate:
      ddl-auto: none   
--- 
spring:
  profiles: local
server:
  port: 8080
---
spring:
  profiles: dev
server:
  port: 8090